# 02 — Definitieve voorbereiding zonder grafieken

ZIPs → vaste cleaning → uuraggregatie → features → target → chronologische splits → modelinvoer. Geen trainingsrapporten of modellen nodig.

## Bijdragen — Messi10

**Raoul Buffels:** dataverwerking en cleaning, EDA en hypothesen, features, modellen,
tuning, evaluatie en documentatie; Citi Bike-frontend en backend.
**Jorre Van Dyck:** hulp bij deployment op Render.
Codex hielp met implementatie, uitleg, tests en uitvoering. Ieder teamlid moet de
eigen keuzes mondeling kunnen uitleggen.

We laden alleen bronverwerking, features en voorbereiding. Er wordt geen plot- of modelmodule geïmporteerd.

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display
locations=[Path.cwd(),Path.cwd().parent,Path.cwd()/'Citybike_full']
ROOT=next(p for p in locations if (p/'citibike').exists())
sys.path.insert(0,str(ROOT))
from citibike.config import SOURCE
from citibike.model_data import prepare_model_data,load_model_data,CONTRACT
from citibike.features import FEATURES,leakage_audit

## Cleaning → aggregatie → features → target

De volgende stap controleert bron- en cachechecksums, harmoniseert schema’s, verwijdert bewezen bronkopieën en bewaart kwaliteitsflags. Geldige starts worden per lokaal uur geteld. Ontbrekende maanden veroorzaken een fout.

Target: geregistreerde vertrekken per uurvak. Kalenderfeatures zijn vooraf bekend; daglags gebruiken afgesloten dagen. Rolling wordt eerst verschoven. De eerste veertien dagen missen historie en vallen uit modeldata. DST gebruikt 24 lokale labels met 0 of 2 fysieke uren waar nodig. Afwijkende bestaande modeldata worden niet overschreven.

In [2]:
prepared=prepare_model_data(SOURCE)
display(pd.DataFrame([CONTRACT]))

Inventariscache 1/175: 2013-citibike-tripdata.zip

Inventariscache 2/175: 2014-citibike-tripdata.zip

Inventariscache 3/175: 2015-citibike-tripdata.zip

Inventariscache 4/175: 2016-citibike-tripdata.zip

Inventariscache 5/175: 2017-citibike-tripdata.zip

Inventariscache 6/175: 2018-citibike-tripdata.zip

Inventariscache 7/175: 2019-citibike-tripdata.zip

Inventariscache 8/175: 2020-citibike-tripdata.zip

Inventariscache 9/175: 2021-citibike-tripdata.zip

Inventariscache 10/175: 2022-citibike-tripdata.zip

Inventariscache 11/175: 2023-citibike-tripdata.zip

Inventariscache 12/175: 202401-citibike-tripdata.zip

Inventariscache 13/175: 202402-citibike-tripdata.zip

Inventariscache 14/175: 202403-citibike-tripdata.zip

Inventariscache 15/175: 202404-citibike-tripdata.zip

Inventariscache 16/175: 202405-citibike-tripdata.zip

Inventariscache 17/175: 202406-citibike-tripdata.zip

Inventariscache 18/175: 202407-citibike-tripdata.zip

Inventariscache 19/175: 202408-citibike-tripdata.zip

Inventariscache 20/175: 202409-citibike-tripdata.zip

Inventariscache 21/175: 202410-citibike-tripdata.zip

Inventariscache 22/175: 202411-citibike-tripdata.zip

Inventariscache 23/175: 202412-citibike-tripdata.zip

Inventariscache 24/175: 202501-citibike-tripdata.zip

Inventariscache 25/175: 202502-citibike-tripdata.zip

Inventariscache 26/175: 202503-citibike-tripdata.zip

Inventariscache 27/175: 202504-citibike-tripdata.zip

Inventariscache 28/175: 202505-citibike-tripdata.zip

Inventariscache 29/175: 202506-citibike-tripdata.zip

Inventariscache 30/175: 202507-citibike-tripdata.zip

Inventariscache 31/175: 202508-citibike-tripdata.zip

Inventariscache 32/175: 202509-citibike-tripdata.zip

Inventariscache 33/175: 202510-citibike-tripdata.zip

Inventariscache 34/175: 202511-citibike-tripdata.zip

Inventariscache 35/175: 202512-citibike-tripdata.zip

Inventariscache 36/175: 202601-citibike-tripdata.zip

Inventariscache 37/175: 202602-citibike-tripdata.zip

Inventariscache 38/175: 202603-citibike-tripdata.zip

Inventariscache 39/175: 202604-citibike-tripdata.zip

Inventariscache 40/175: 202605-citibike-tripdata.zip

Inventariscache 41/175: 202606-citibike-tripdata.zip

Inventariscache 42/175: 202607-citibike-tripdata.zip

Inventariscache 43/175: 202608-citibike-tripdata.zip

Inventariscache 44/175: JC-201509-citibike-tripdata.csv.zip

Inventariscache 45/175: JC-201510-citibike-tripdata.csv.zip

Inventariscache 46/175: JC-201511-citibike-tripdata.csv.zip

Inventariscache 47/175: JC-201512-citibike-tripdata.csv.zip

Inventariscache 48/175: JC-201601-citibike-tripdata.csv.zip

Inventariscache 49/175: JC-201602-citibike-tripdata.csv.zip

Inventariscache 50/175: JC-201603-citibike-tripdata.csv.zip

Inventariscache 51/175: JC-201604-citibike-tripdata.csv.zip

Inventariscache 52/175: JC-201605-citibike-tripdata.csv.zip

Inventariscache 53/175: JC-201606-citibike-tripdata.csv.zip

Inventariscache 54/175: JC-201607-citibike-tripdata.csv.zip

Inventariscache 55/175: JC-201608-citibike-tripdata.csv.zip

Inventariscache 56/175: JC-201609-citibike-tripdata.csv.zip

Inventariscache 57/175: JC-201610-citibike-tripdata.csv.zip

Inventariscache 58/175: JC-201611-citibike-tripdata.csv.zip

Inventariscache 59/175: JC-201612-citibike-tripdata.csv.zip

Inventariscache 60/175: JC-201701-citibike-tripdata.csv.zip

Inventariscache 61/175: JC-201702-citibike-tripdata.csv.zip

Inventariscache 62/175: JC-201703-citibike-tripdata.csv.zip

Inventariscache 63/175: JC-201704-citibike-tripdata.csv.zip

Inventariscache 64/175: JC-201705-citibike-tripdata.csv.zip

Inventariscache 65/175: JC-201706-citibike-tripdata.csv.zip

Inventariscache 66/175: JC-201707-citibike-tripdata.csv.zip

Inventariscache 67/175: JC-201708 citibike-tripdata.csv.zip

Inventariscache 68/175: JC-201709-citibike-tripdata.csv.zip

Inventariscache 69/175: JC-201710-citibike-tripdata.csv.zip

Inventariscache 70/175: JC-201711-citibike-tripdata.csv.zip

Inventariscache 71/175: JC-201712-citibike-tripdata.csv.zip

Inventariscache 72/175: JC-201801-citibike-tripdata.csv.zip

Inventariscache 73/175: JC-201802-citibike-tripdata.csv.zip

Inventariscache 74/175: JC-201803-citibike-tripdata.csv.zip

Inventariscache 75/175: JC-201804-citibike-tripdata.csv.zip

Inventariscache 76/175: JC-201805-citibike-tripdata.csv.zip

Inventariscache 77/175: JC-201806-citibike-tripdata.csv.zip

Inventariscache 78/175: JC-201807-citibike-tripdata.csv.zip

Inventariscache 79/175: JC-201808-citibike-tripdata.csv.zip

Inventariscache 80/175: JC-201809-citibike-tripdata.csv.zip

Inventariscache 81/175: JC-201810-citibike-tripdata.csv.zip

Inventariscache 82/175: JC-201811-citibike-tripdata.csv.zip

Inventariscache 83/175: JC-201812-citibike-tripdata.csv.zip

Inventariscache 84/175: JC-201901-citibike-tripdata.csv.zip

Inventariscache 85/175: JC-201902-citibike-tripdata.csv.zip

Inventariscache 86/175: JC-201903-citibike-tripdata.csv.zip

Inventariscache 87/175: JC-201904-citibike-tripdata.csv.zip

Inventariscache 88/175: JC-201905-citibike-tripdata.csv.zip

Inventariscache 89/175: JC-201906-citibike-tripdata.csv.zip

Inventariscache 90/175: JC-201907-citibike-tripdata.csv.zip

Inventariscache 91/175: JC-201908-citibike-tripdata.csv.zip

Inventariscache 92/175: JC-201909-citibike-tripdata.csv.zip

Inventariscache 93/175: JC-201910-citibike-tripdata.csv.zip

Inventariscache 94/175: JC-201911-citibike-tripdata.csv.zip

Inventariscache 95/175: JC-201912-citibike-tripdata.csv.zip

Inventariscache 96/175: JC-202001-citibike-tripdata.csv.zip

Inventariscache 97/175: JC-202002-citibike-tripdata.csv.zip

Inventariscache 98/175: JC-202003-citibike-tripdata.csv.zip

Inventariscache 99/175: JC-202004-citibike-tripdata.csv.zip

Inventariscache 100/175: JC-202005-citibike-tripdata.csv.zip

Inventariscache 101/175: JC-202006-citibike-tripdata.csv.zip

Inventariscache 102/175: JC-202007-citibike-tripdata.csv.zip

Inventariscache 103/175: JC-202008-citibike-tripdata.csv.zip

Inventariscache 104/175: JC-202009-citibike-tripdata.csv.zip

Inventariscache 105/175: JC-202010-citibike-tripdata.csv.zip

Inventariscache 106/175: JC-202011-citibike-tripdata.csv.zip

Inventariscache 107/175: JC-202012-citibike-tripdata.csv.zip

Inventariscache 108/175: JC-202101-citibike-tripdata.csv.zip

Inventariscache 109/175: JC-202102-citibike-tripdata.csv.zip

Inventariscache 110/175: JC-202103-citibike-tripdata.csv.zip

Inventariscache 111/175: JC-202104-citibike-tripdata.csv.zip

Inventariscache 112/175: JC-202105-citibike-tripdata.csv.zip

Inventariscache 113/175: JC-202106-citibike-tripdata.csv.zip

Inventariscache 114/175: JC-202107-citibike-tripdata.csv.zip

Inventariscache 115/175: JC-202108-citibike-tripdata.csv.zip

Inventariscache 116/175: JC-202109-citibike-tripdata.csv.zip

Inventariscache 117/175: JC-202110-citibike-tripdata.csv.zip

Inventariscache 118/175: JC-202111-citibike-tripdata.csv.zip

Inventariscache 119/175: JC-202112-citibike-tripdata.csv.zip

Inventariscache 120/175: JC-202201-citibike-tripdata.csv.zip

Inventariscache 121/175: JC-202202-citibike-tripdata.csv.zip

Inventariscache 122/175: JC-202203-citibike-tripdata.csv.zip

Inventariscache 123/175: JC-202204-citibike-tripdata.csv.zip

Inventariscache 124/175: JC-202205-citibike-tripdata.csv.zip

Inventariscache 125/175: JC-202206-citibike-tripdata.csv.zip

Inventariscache 126/175: JC-202207-citbike-tripdata.csv.zip

Inventariscache 127/175: JC-202208-citibike-tripdata.csv.zip

Inventariscache 128/175: JC-202209-citibike-tripdata.csv.zip

Inventariscache 129/175: JC-202210-citibike-tripdata.csv.zip

Inventariscache 130/175: JC-202211-citibike-tripdata.csv.zip

Inventariscache 131/175: JC-202212-citibike-tripdata.csv.zip

Inventariscache 132/175: JC-202301-citibike-tripdata.csv.zip

Inventariscache 133/175: JC-202302-citibike-tripdata.csv.zip

Inventariscache 134/175: JC-202303-citibike-tripdata.csv.zip

Inventariscache 135/175: JC-202304-citibike-tripdata.csv.zip

Inventariscache 136/175: JC-202305-citibike-tripdata.csv.zip

Inventariscache 137/175: JC-202306-citibike-tripdata.csv.zip

Inventariscache 138/175: JC-202307-citibike-tripdata.csv.zip

Inventariscache 139/175: JC-202308-citibike-tripdata.csv.zip

Inventariscache 140/175: JC-202309-citibike-tripdata.csv.zip

Inventariscache 141/175: JC-202310-citibike-tripdata.csv.zip

Inventariscache 142/175: JC-202311-citibike-tripdata.csv.zip

Inventariscache 143/175: JC-202312-citibike-tripdata.csv.zip

Inventariscache 144/175: JC-202401-citibike-tripdata.csv.zip

Inventariscache 145/175: JC-202402-citibike-tripdata.csv.zip

Inventariscache 146/175: JC-202403-citibike-tripdata.csv.zip

Inventariscache 147/175: JC-202404-citibike-tripdata.csv.zip

Inventariscache 148/175: JC-202405-citibike-tripdata.csv.zip

Inventariscache 149/175: JC-202406-citibike-tripdata.csv.zip

Inventariscache 150/175: JC-202407-citibike-tripdata.csv.zip

Inventariscache 151/175: JC-202408-citibike-tripdata.csv.zip

Inventariscache 152/175: JC-202409-citibike-tripdata.csv.zip

Inventariscache 153/175: JC-202410-citibike-tripdata.csv.zip

Inventariscache 154/175: JC-202411-citibike-tripdata.csv.zip

Inventariscache 155/175: JC-202412-citibike-tripdata.csv.zip

Inventariscache 156/175: JC-202501-citibike-tripdata.csv.zip

Inventariscache 157/175: JC-202502-citibike-tripdata.csv.zip

Inventariscache 158/175: JC-202503-citibike-tripdata.csv.zip

Inventariscache 159/175: JC-202504-citibike-tripdata.csv.zip

Inventariscache 160/175: JC-202505-citibike-tripdata.csv.zip

Inventariscache 161/175: JC-202506-citibike-tripdata.csv.zip

Inventariscache 162/175: JC-202507-citibike-tripdata.csv.zip

Inventariscache 163/175: JC-202508-citibike-tripdata.csv.zip

Inventariscache 164/175: JC-202509-citibike-tripdata.csv.zip

Inventariscache 165/175: JC-202510-citibike-tripdata.zip

Inventariscache 166/175: JC-202511-citibike-tripdata.csv.zip

Inventariscache 167/175: JC-202512-citibike-tripdata.csv.zip

Inventariscache 168/175: JC-202601-citibike-tripdata.zip

Inventariscache 169/175: JC-202602-citibike-tripdata.csv.zip

Inventariscache 170/175: JC-202603-citibike-tripdata.csv.zip

Inventariscache 171/175: JC-202604-citibike-tripdata.zip

Inventariscache 172/175: JC-202605-citibike-tripdata.csv.zip

Inventariscache 173/175: JC-202606-citibike-tripdata.csv.zip

Inventariscache 174/175: JC-202607-citibike-tripdata.csv.zip

Inventariscache 175/175: JC-202608-citibike-tripdata.csv.zip

Cache JC 2015-09

Cache JC 2015-10

Cache JC 2015-11

Cache JC 2015-12

Cache JC 2016-01

Cache JC 2016-02

Cache JC 2016-03

Cache JC 2016-04

Cache JC 2016-05

Cache JC 2016-06

Cache JC 2016-07

Cache JC 2016-08

Cache JC 2016-09

Cache JC 2016-10

Cache JC 2016-11

Cache JC 2016-12

Cache JC 2017-01

Cache JC 2017-02

Cache JC 2017-03

Cache JC 2017-04

Cache JC 2017-05

Cache JC 2017-06

Cache JC 2017-07

Cache JC 2017-08

Cache JC 2017-09

Cache JC 2017-10

Cache JC 2017-11

Cache JC 2017-12

Cache JC 2018-01

Cache JC 2018-02

Cache JC 2018-03

Cache JC 2018-04

Cache JC 2018-05

Cache JC 2018-06

Cache JC 2018-07

Cache JC 2018-08

Cache JC 2018-09

Cache JC 2018-10

Cache JC 2018-11

Cache JC 2018-12

Cache JC 2019-01

Cache JC 2019-02

Cache JC 2019-03

Cache JC 2019-04

Cache JC 2019-05

Cache JC 2019-06

Cache JC 2019-07

Cache JC 2019-08

Cache JC 2019-09

Cache JC 2019-10

Cache JC 2019-11

Cache JC 2019-12

Cache JC 2020-01

Cache JC 2020-02

Cache JC 2020-03

Cache JC 2020-04

Cache JC 2020-05

Cache JC 2020-06

Cache JC 2020-07

Cache JC 2020-08

Cache JC 2020-09

Cache JC 2020-10

Cache JC 2020-11

Cache JC 2020-12

Cache JC 2021-01

Cache JC 2021-02

Cache JC 2021-03

Cache JC 2021-04

Cache JC 2021-05

Cache JC 2021-06

Cache JC 2021-07

Cache JC 2021-08

Cache JC 2021-09

Cache JC 2021-10

Cache JC 2021-11

Cache JC 2021-12

Cache JC 2022-01

Cache JC 2022-02

Cache JC 2022-03

Cache JC 2022-04

Cache JC 2022-05

Cache JC 2022-06

Cache JC 2022-07

Cache JC 2022-08

Cache JC 2022-09

Cache JC 2022-10

Cache JC 2022-11

Cache JC 2022-12

Cache JC 2023-01

Cache JC 2023-02

Cache JC 2023-03

Cache JC 2023-04

Cache JC 2023-05

Cache JC 2023-06

Cache JC 2023-07

Cache JC 2023-08

Cache JC 2023-09

Cache JC 2023-10

Cache JC 2023-11

Cache JC 2023-12

Cache JC 2024-01

Cache JC 2024-02

Cache JC 2024-03

Cache JC 2024-04

Cache JC 2024-05

Cache JC 2024-06

Cache JC 2024-07

Cache JC 2024-08

Cache JC 2024-09

Cache JC 2024-10

Cache JC 2024-11

Cache JC 2024-12

Cache JC 2025-01

Cache JC 2025-02

Cache JC 2025-03

Cache JC 2025-04

Cache JC 2025-05

Cache JC 2025-06

Cache JC 2025-07

Cache JC 2025-08

Cache JC 2025-09

Cache JC 2025-10

Cache JC 2025-11

Cache JC 2025-12

Cache JC 2026-01

Cache JC 2026-02

Cache JC 2026-03

Cache JC 2026-04

Cache JC 2026-05

Cache JC 2026-06

Cache JC 2026-07

Cache JC 2026-08

Cache NYC 2013-06

Cache NYC 2013-07

Cache NYC 2013-08

Cache NYC 2013-09

Cache NYC 2013-10

Cache NYC 2013-11

Cache NYC 2013-12

Cache NYC 2014-01

Cache NYC 2014-02

Cache NYC 2014-03

Cache NYC 2014-04

Cache NYC 2014-05

Cache NYC 2014-06

Cache NYC 2014-07

Cache NYC 2014-08

Cache NYC 2014-09

Cache NYC 2014-10

Cache NYC 2014-11

Cache NYC 2014-12

Cache NYC 2015-01

Cache NYC 2015-02

Cache NYC 2015-03

Cache NYC 2015-04

Cache NYC 2015-05

Cache NYC 2015-06

Cache NYC 2015-07

Cache NYC 2015-08

Cache NYC 2015-09

Cache NYC 2015-10

Cache NYC 2015-11

Cache NYC 2015-12

Cache NYC 2016-01

Cache NYC 2016-02

Cache NYC 2016-03

Cache NYC 2016-04

Cache NYC 2016-05

Cache NYC 2016-06

Cache NYC 2016-07

Cache NYC 2016-08

Cache NYC 2016-09

Cache NYC 2016-10

Cache NYC 2016-11

Cache NYC 2016-12

Cache NYC 2017-01

Cache NYC 2017-02

Cache NYC 2017-03

Cache NYC 2017-04

Cache NYC 2017-05

Cache NYC 2017-06

Cache NYC 2017-07

Cache NYC 2017-08

Cache NYC 2017-09

Cache NYC 2017-10

Cache NYC 2017-11

Cache NYC 2017-12

Cache NYC 2018-01

Cache NYC 2018-02

Cache NYC 2018-03

Cache NYC 2018-04

Cache NYC 2018-05

Cache NYC 2018-06

Cache NYC 2018-07

Cache NYC 2018-08

Cache NYC 2018-09

Cache NYC 2018-10

Cache NYC 2018-11

Cache NYC 2018-12

Cache NYC 2019-01

Cache NYC 2019-02

Cache NYC 2019-03

Cache NYC 2019-04

Cache NYC 2019-05

Cache NYC 2019-06

Cache NYC 2019-07

Cache NYC 2019-08

Cache NYC 2019-09

Cache NYC 2019-10

Cache NYC 2019-11

Cache NYC 2019-12

Cache NYC 2020-01

Cache NYC 2020-02

Cache NYC 2020-03

Cache NYC 2020-04

Cache NYC 2020-05

Cache NYC 2020-06

Cache NYC 2020-07

Cache NYC 2020-08

Cache NYC 2020-09

Cache NYC 2020-10

Cache NYC 2020-11

Cache NYC 2020-12

Cache NYC 2021-01

Cache NYC 2021-02

Cache NYC 2021-03

Cache NYC 2021-04

Cache NYC 2021-05

Cache NYC 2021-06

Cache NYC 2021-07

Cache NYC 2021-08

Cache NYC 2021-09

Cache NYC 2021-10

Cache NYC 2021-11

Cache NYC 2021-12

Cache NYC 2022-01

Cache NYC 2022-02

Cache NYC 2022-03

Cache NYC 2022-04

Cache NYC 2022-05

Cache NYC 2022-06

Cache NYC 2022-07

Cache NYC 2022-08

Cache NYC 2022-09

Cache NYC 2022-10

Cache NYC 2022-11

Cache NYC 2022-12

Cache NYC 2023-01

Cache NYC 2023-02

Cache NYC 2023-03

Cache NYC 2023-04

Cache NYC 2023-05

Cache NYC 2023-06

Cache NYC 2023-07

Cache NYC 2023-08

Cache NYC 2023-09

Cache NYC 2023-10

Cache NYC 2023-11

Cache NYC 2023-12

Cache NYC 2024-01

Cache NYC 2024-02

Cache NYC 2024-03

Cache NYC 2024-04

Cache NYC 2024-05

Cache NYC 2024-06

Cache NYC 2024-07

Cache NYC 2024-08

Cache NYC 2024-09

Cache NYC 2024-10

Cache NYC 2024-11

Cache NYC 2024-12

Cache NYC 2025-01

Cache NYC 2025-02

Cache NYC 2025-03

Cache NYC 2025-04

Cache NYC 2025-05

Cache NYC 2025-06

Cache NYC 2025-07

Cache NYC 2025-08

Cache NYC 2025-09

Cache NYC 2025-10

Cache NYC 2025-11

Cache NYC 2025-12

Cache NYC 2026-01

Cache NYC 2026-02

Cache NYC 2026-03

Cache NYC 2026-04

Cache NYC 2026-05

Cache NYC 2026-06

Cache NYC 2026-07

Cache NYC 2026-08

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,target,area,prediction_time,history_days,features,window_years,train_end_exclusive,validation_end_exclusive,test_start,test_end_exclusive
0,hourly_demand,NYC,00:00 America/New_York op voorspeldag D,14,"[hour_sin, hour_cos, weekday_sin, weekday_cos,...",None,2026-05-01,2026-07-01,2026-07-01,2026-09-01

## Splits en voorbereide uitvoer

Training: vóór mei; validatie: mei–juni. De testpartitions juli–augustus blijven afgeschermd. Deze voorbereiding vereist geen evaluatie-lock en leest geen testlabels. De vijf folds komen alleen uit training.

In [3]:
training,validation,prepared=load_model_data()
display(pd.DataFrame([{k:v for k,v in prepared.items() if k not in ['folds','contract']}]))
display(pd.DataFrame(prepared['folds']))
display(training[['timestamp','rides']+FEATURES].tail(3))
display(validation[['timestamp','rides']+FEATURES].head(3))

,prepared_at,path,sha256,dataset_fingerprint,existing_dataset_equal,rows,train_rows,validation_rows,train_start,train_end_exclusive,validation_start,validation_end_exclusive,test_start,test_end_exclusive,fold_fingerprint,training_results_required,test_labels_read,test_preparation
0,2026-10-14T15:08:33.145076+00:00,C:\Deeplearning\CloudAI\Citybike_full\data\mod...,2be4c1fa94f1ee4657020c8912af03e6aadd7735d8ba0d...,409eb1829fa0565f464bbd031cc4e17c8c64f7c9aae466...,True,114336,112872,1464,2013-06-15 00:00:00,2026-05-01,2026-05-01,2026-07-01,2026-07-01,2026-09-01,59238f467d526664e56943f96d102928ede96e4e371fec...,False,False,Ruwe testpartitions technisch opgeschoond; tes...

,train_start,train_stop,validation_start,validation_stop,train_last_day,validation_first_day,validation_last_day
0,0,109512,109512,110184,2025-12-11,2025-12-12,2026-01-08
1,0,110184,110184,110856,2026-01-08,2026-01-09,2026-02-05
2,0,110856,110856,111528,2026-02-05,2026-02-06,2026-03-05
3,0,111528,111528,112200,2026-03-05,2026-03-06,2026-04-02
4,0,112200,112200,112872,2026-04-02,2026-04-03,2026-04-30

,timestamp,rides,hour_sin,hour_cos,weekday_sin,weekday_cos,year_sin,year_cos,is_weekend,clock_hours,lag_1d,lag_2d,lag_7d,lag_14d,same_hour_mean_7d,previous_day_total
112869,2026-04-30 21:00:00,5418,-0.707107,0.707107,0.433884,-0.900969,0.888682,-0.458524,0,1,2645.0,5156.0,6557.0,7253.0,3941.714286,141454.0
112870,2026-04-30 22:00:00,4439,-0.500000,0.866025,0.433884,-0.900969,0.888682,-0.458524,0,1,1449.0,3939.0,5855.0,5865.0,3102.857143,141454.0
112871,2026-04-30 23:00:00,2875,-0.258819,0.965926,0.433884,-0.900969,0.888682,-0.458524,0,1,620.0,2571.0,3667.0,3831.0,2091.142857,141454.0

,timestamp,rides,hour_sin,hour_cos,weekday_sin,weekday_cos,year_sin,year_cos,is_weekend,clock_hours,lag_1d,lag_2d,lag_7d,lag_14d,same_hour_mean_7d,previous_day_total
0,2026-05-01 00:00:00,1702,0.000000,1.000000,-0.433884,-0.900969,0.880663,-0.473744,0,1,493.0,1196.0,2123.0,2295.0,1271.000000,139724.0
1,2026-05-01 01:00:00,948,0.258819,0.965926,-0.433884,-0.900969,0.880663,-0.473744,0,1,166.0,545.0,1068.0,1249.0,740.714286,139724.0
2,2026-05-01 02:00:00,523,0.500000,0.866025,-0.433884,-0.900969,0.880663,-0.473744,0,1,136.0,383.0,682.0,708.0,492.714286,139724.0

## Beschikbaarheid om 00:00

Geen telling op de voorspeldag beïnvloedt eerdere features. Historische tellingen moeten tijdig beschikbaar zijn; maandarchieven bewijzen geen live feed. De modelnotebooks laden exact deze output.

In [4]:
display(pd.DataFrame(leakage_audit()))

,feature,available_at,available_at_prediction,availability_assumption,target_information,leaks
0,hour_sin,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
1,hour_cos,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
2,weekday_sin,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
3,weekday_cos,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
4,year_sin,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
5,year_cos,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
6,is_weekend,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
7,clock_hours,kalender bekend vóór 00:00 op D,True,kalender deterministisch bekend,geen doelwaarden,False
8,lag_1d,uitsluitend volledige dagen vóór D; rolling ee...,voorwaardelijk: externe tellingen bekend vóór D,Offline backtest veronderstelt tijdige externe...,historische doelwaarden toegestaan,False
9,lag_2d,uitsluitend volledige dagen vóór D; rolling ee...,voorwaardelijk: externe tellingen bekend vóór D,Offline backtest veronderstelt tijdige externe...,historische doelwaarden toegestaan,False
10,lag_7d,uitsluitend volledige dagen vóór D; rolling ee...,voorwaardelijk: externe tellingen bekend vóór D,Offline backtest veronderstelt tijdige externe...,historische doelwaarden toegestaan,False
11,lag_14d,uitsluitend volledige dagen vóór D; rolling ee...,voorwaardelijk: externe tellingen bekend vóór D,Offline backtest veronderstelt tijdige externe...,historische doelwaarden toegestaan,False
12,same_hour_mean_7d,uitsluitend volledige dagen vóór D; rolling ee...,voorwaardelijk: externe tellingen bekend vóór D,Offline backtest veronderstelt tijdige externe...,historische doelwaarden toegestaan,False
13,previous_day_total,uitsluitend volledige dagen vóór D; rolling ee...,voorwaardelijk: externe tellingen bekend vóór D,Offline backtest veronderstelt tijdige externe...,historische doelwaarden toegestaan,False